{% set name = "specutils" %}
{% set version = "0.6.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1d587b4b65317d25de6d358fbfd2b19021fc23f8474859d1c07bd80ba6ea9b8

build:
  noarch: python
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3
    - setuptools
    - astropy >=3.1,<4
    - six
    - gwcs <0.12
    - scipy
  run:
    - python >=3
    - astropy >=3.1,<4
    - six
    - gwcs <0.12
    - scipy

test:
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.wcs
    - specutils.utils

about:
  home: http://specutils.readthedocs.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: 'LICENSE.rst'
  summary: Astropy affiliated package for astronomical spectral operations.
  description: "The specutils package implements base classes and utilities for\r\ninteracting with astronomical spectra in Python and the Astropy\r\nproject.  It is intended for eventual merger with the\
    \ `astropy`\r\npackage, but for now is being developed independently."
  doc_url: http://specutils.readthedocs.io/
  dev_url: https://github.com/astropy/specutils

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - nmearl
    - crawfordsm
    - keflavich
