{% set name = "specutils" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 998c11f1a885c41a5a09844750543dcc1470b42c134468accfb202c9fb1edc32

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - astropy >=4.1
    - gwcs !=0.16
    - asdf >=2.5
    - scipy

test:
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.utils

about:
  home: http://specutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for astronomical spectral operations.
  description: |
    The specutils package implements base classes and utilities for
    interacting with astronomical spectra in Python and the Astropy project.
    It is intended for eventual merger with the `astropy` package, but for now
    is being developed independently.
  doc_url: http://specutils.readthedocs.io/
  dev_url: https://github.com/astropy/specutils

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - nmearl
    - crawfordsm
    - keflavich
    - eteq
